import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Survey",
  description: "Generated by create next app",
  icons:{
    icon:['favicon.ico?v=4']
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-montserrat vertical-scrollbar">
        {children}
      </body>
    </html>
  );
}
