export const questions = [
  "Text Block",
  "Single line Text Input",
  "Multiline Text Input",
  "Number Input",
  "Number With Auto Code",
  "Decimal Input",
  "Email",
  "Phone Number",
  "Radio Button",
  "Radio Button With Other",
  "DropDown",
  "DropDown With Other",
  "Checkbox List",
  "Checkbox List With Other",
  "Number Point",
  "Rating",
  "Date",
];

export const advanceQuestions = [
  "Radio Button With Text",
  "DropDown Grid",
  "DropDown With Other Grid",
  "Single line Text Grid",
  "Number Grid",
  "Decimal Grid",
  "Radio Grid",
  "Radio Grid With Other",
  "Checkbox With Text",
  "Checkbox Grid",
  "Checkbox Grid With Other",
  "Number Point Grid",
  "Contact Form",
  "Address",
];
